name: Format Code with Prettier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Prettier formatting
        run: |
          npm run format || echo "::warning::Prettier ran with errors, but continuing."

      - name: Create new branch and commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b format-code-branch
          git add -A
          git commit -m "chore: format code with Prettier"
          
          # Pull the latest changes from the remote to ensure you're in sync
          git pull origin main --rebase
          
          # Push to the remote repository
          git push origin format-code-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Format code with Prettier"
          body: |
            This pull request includes the changes made to format the codebase using Prettier. 

            **Summary of changes**:
            - Applied Prettier to format all files within the project.
            - Fixed inconsistent indentation, spacing, and line breaks in several files.
            - Cleaned up and standardized formatting across all supported file types.

            **Why these changes were made**:
            - **Code consistency**: Applying Prettier ensures a consistent style throughout the codebase, improving readability and maintainability.
            - **Automating formatting**: Prettier removes the need for manual formatting, reducing errors and conflicts that arise from formatting disagreements among developers.
            - **Improved readability**: A properly formatted codebase helps all team members quickly navigate, understand, and contribute to the project.

            **How to verify**:
            - Review the commit history to ensure that Prettier ran successfully.
            - Review the changes made to ensure no logical errors were introduced.

            This PR is part of an ongoing effort to keep the codebase clean and organized, ensuring smooth collaboration and efficient code management.

          base: main
          branch: format-code-branch
